version: '3.3'
services:
    server:
        restart: always
        deploy:
            replicas: 1
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env
